#! /usr/bin/env ruby

require "rubygems"
require "net/ssh"

puts "Cleaning"
puts `rm -rf products/*`

puts "Documenting"
puts `jazzy --xcodebuild-arguments -scheme,HoneyBee  --output products/docs/`

version_string = `/usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' HoneyBee/Info.plist`.strip

puts "Pushing"
puts `cd products; rsync -r docs iamwebservices@iamwebservices.com:iamwebservices/current/public/HoneyBee/#{version_string}/`

spec = %[
Pod::Spec.new do |s|
  s.name         = "HoneyBee"
  s.version      = "#{version_string}"
  s.summary      = "A swift library to increase the expressiveness of asynchronous and concurrent programming."

  s.homepage     = "http://HoneyBee.link/#{version_string}/docs/index.html"
	s.documentation_url = s.homepage

  s.license      = { :type=>"MIT" }

  s.author       = { "Alex Lynch" => "alex@iamapps.net" }

  s.ios.deployment_target = "10.0"
  s.osx.deployment_target = "10.11"
  s.tvos.deployment_target = "10.0"
  s.pod_target_xcconfig = { "SWIFT_VERSION" => "4.0" }

  s.source       = { :git => "https://bitbucket.org/iam_apps/honeybee.git", :tag=>"v#{version_string}"}

  s.source_files = "HoneyBee/*.swift"
end	
]

File.open("HoneyBee.podspec",'w') {|f| f.puts spec}

puts "Publishing"
puts `pod trunk push --swift-version=4.0 HoneyBee.podspec`

puts "Linking Current"

Net::SSH.start("iamwebservices.com", "iamwebservices") do |ssh|
  result = ssh.exec!("cd iamwebservices/current/public/HoneyBee; rm current; ln -sf #{version_string} current; ls -l current")
  puts result
end
