#! /usr/bin/env ruby

require "rubygems"
require "net/ssh"
require "jazzy"
require "katip"

version_string = ARGV.shift
username = ARGV.shift

if username == nil || username == nil
	puts "Expected: make_release <version_string> <username>"
	exit
end

puts "Versioning"
puts `/usr/libexec/PlistBuddy -c 'Set CFBundleShortVersionString #{version_string}' HoneyBee/Info.plist`

puts `katip ChangeLog.md`

spec = %[
Pod::Spec.new do |s|
  s.name         = "HoneyBee"
  s.version      = "#{version_string}"
  s.summary      = "A swift library to increase the expressiveness of asynchronous and concurrent programming."

  s.homepage     = "http://HoneyBee.link/#{version_string}/docs/index.html"
	s.documentation_url = s.homepage

  s.license      = { :type=>"MIT" }

  s.author       = { "Alex Lynch" => "alex@iamapps.net" }

  s.ios.deployment_target = "10.0"
  s.osx.deployment_target = "10.11"
  s.tvos.deployment_target = "10.0"
  s.pod_target_xcconfig = { "SWIFT_VERSION" => "4.1" }

  s.source       = { :git => "https://bitbucket.org/iam_apps/honeybee.git", :tag=>"v#{version_string}"}

  s.source_files = "HoneyBee/*.swift"
end	
]

File.open("HoneyBee.podspec",'w') {|f| f.puts spec}

puts `git add HoneyBee/Info.plist ChangeLog.md HoneyBee.podspec`
puts `git commit -m "Mark as v#{version_string}"`
puts `git tag v#{version_string}`
puts `git push --tags`


puts "Documenting"
puts `rm -rf products/*`
puts `jazzy --xcodebuild-arguments -scheme,HoneyBee  --output products/docs/`
puts `cd products; rsync -r docs #{username}@HoneyBee.link:#{username}/current/public/HoneyBee/#{version_string}/`


puts "Publishing"
puts `pod trunk push --swift-version=4.0 HoneyBee.podspec`


puts "Linking Current"
Net::SSH.start("HoneyBee.link", username) do |ssh|
  result = ssh.exec!("cd #{username}/current/public/HoneyBee; rm current; ln -sf #{version_string} current; ls -l current")
  puts result
end

puts "Updating CocoaPods Homepage"
puts `curl "http://207.254.41.223:4567/redeploy/HoneyBee/latest"`
