#! /usr/bin/env ruby

puts "Cleaning"
puts `rm -rf products/*`

puts "Building"
puts `xcodebuild archive -project HoneyBee.xcodeproj -scheme HoneyBee`

puts "Documenting"
puts `jazzy --xcodebuild-arguments -scheme,HoneyBee  --output products/docs/`

puts "Copying"
puts `rsync HoneyBee/*.swift products/HoneyBee/`
puts `rsync LICENSE products/`

version_string = `/usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' HoneyBee/Info.plist`.strip

puts "Zipping"
zip_file = "HoneyBee-#{version_string}.zip"
puts `cd products; /usr/bin/zip -r #{zip_file} LICENSE HoneyBee`

puts "Pushing"
puts `cd products; rsync -r #{zip_file} docs iamwebservices@iamwebservices.com:iamwebservices/current/public/HoneyBee/#{version_string}/`

spec = %[
Pod::Spec.new do |s|
  s.name         = "HoneyBee"
  s.version      = "#{version_string}"
  s.summary      = "A swift library to increase the expressiveness of asynchronous and concurent code."

  s.description  = <<-DESC
	HoneyBee reduces the clutter and complexity of asynchronous and concurent code. 
	By handing the noise of data routing and error handling, HoneyBee provides a higher-level, more expressive perspective on asynchronous programming.
                   DESC

  s.homepage     = "http://iamapps.net/HoneyBee/#{version_string}/docs/index.html"

  s.license      = { :type=>"MIT", :file => 'LICENSE' }

  s.author       = { "Alex Lynch" => "alex@iamapps.com" }

  s.ios.deployment_target = "10.0"
  s.osx.deployment_target = "10.10"
  s.watchos.deployment_target = "4.0"
  s.tvos.deployment_target = "10.0"

  s.source       = { :http => "http://iamapps.net/HoneyBee/#{version_string}/HoneyBee-#{version_string}.zip"}

  s.source_files = "HoneyBee/*.swift"

end	
]

File.open("HoneyBee.podspec",'w') {|f| f.puts spec}

puts "Publishing"
puts `pod trunk push --swift-version=4.0 HoneyBee.podspec`